# Create a postgis service using the postgis/postgis image.
services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  run-linter:
    build: .
    volumes:
      - .:/workspace/assignment01
    entrypoint: ["/workspace/assignment01/__entrypoints__/run_linter.sh"]

  run-tests:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_NAME: postgres
    volumes:
      - .:/workspace/assignment01
    entrypoint: ["/workspace/assignment01/__entrypoints__/run_tests.sh"]
